# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            WebXR Pseudo-haptics
tagline:          Demonstraions of pseudo-haptics using WebXR
description:      Demonstraions of pseudo-haptics using WebXR
url:              https://kn1cht.github.io
baseurl:          /webxr-pseudo-haptics
ogp-img:          https://kn1cht.github.io/webxr-pseudo-haptics/public/thumb.png

author:
  name:           'Kenichi Ito'
  url:            https://k-ito.dev/


# Custom vars
version:          0.9.0
